
// This file has been generated by the GUI designer. Do not modify.
namespace battle
{
	public partial class targetting
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.CheckButton checkbutton2;
		private global::Gtk.CheckButton checkbutton3;
		private global::Gtk.CheckButton checkbutton4;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget battle.targetting
			this.Name = "battle.targetting";
			this.Title = global::Mono.Unix.Catalog.GetString ("Targetting");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(9));
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child battle.targetting.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.checkbutton2 = new global::Gtk.CheckButton ();
			this.checkbutton2.CanFocus = true;
			this.checkbutton2.Name = "checkbutton2";
			this.checkbutton2.Label = "";
			this.checkbutton2.DrawIndicator = true;
			this.checkbutton2.UseUnderline = true;
			this.fixed2.Add (this.checkbutton2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.checkbutton2]));
			w2.X = 4;
			w2.Y = 4;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.checkbutton3 = new global::Gtk.CheckButton ();
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = "";
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.fixed2.Add (this.checkbutton3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.checkbutton3]));
			w3.X = 4;
			w3.Y = 23;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.checkbutton4 = new global::Gtk.CheckButton ();
			this.checkbutton4.CanFocus = true;
			this.checkbutton4.Name = "checkbutton4";
			this.checkbutton4.Label = "";
			this.checkbutton4.DrawIndicator = true;
			this.checkbutton4.UseUnderline = true;
			this.fixed2.Add (this.checkbutton4);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.checkbutton4]));
			w4.X = 5;
			w4.Y = 43;
			w1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed2]));
			w5.Position = 0;
			// Internal child battle.targetting.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonCancel]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonOk]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 212;
			this.DefaultHeight = 132;
			this.Show ();
			this.Close += new global::System.EventHandler (this.OnClose);
			this.checkbutton2.Toggled += new global::System.EventHandler (this.OnCheckbutton2Toggled);
			this.checkbutton3.Toggled += new global::System.EventHandler (this.OnCheckbutton3Toggled);
			this.checkbutton4.Toggled += new global::System.EventHandler (this.OnCheckbutton4Toggled);
			this.buttonCancel.Released += new global::System.EventHandler (this.OnButtonCancelReleased);
			this.buttonOk.Released += new global::System.EventHandler (this.OnButtonOkReleased);
		}
	}
}
