
// This file has been generated by the GUI designer. Do not modify.
namespace battle
{
	public partial class MainWindow
	{
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.Table table1;
		private global::Gtk.Fixed fixed10;
		private global::Gtk.Label PC3Name;
		private global::Gtk.Label PC3HP;
		private global::Gtk.Label PC3MP;
		private global::Gtk.Label PC3Status;
		private global::Gtk.Fixed fixedNPC1;
		private global::Gtk.Label NPC1Name;
		private global::Gtk.Label NPC1HP;
		private global::Gtk.Label NPC1MP;
		private global::Gtk.Label NPC1Status;
		private global::Gtk.Fixed fixedNPC2;
		private global::Gtk.Label NPC2Name;
		private global::Gtk.Label NPC2HP;
		private global::Gtk.Label NPC2MP;
		private global::Gtk.Label NPC2Status;
		private global::Gtk.Fixed fixedNPC3;
		private global::Gtk.Label NPC3Name;
		private global::Gtk.Label NPC3HP;
		private global::Gtk.Label NPC3MP;
		private global::Gtk.Label NPC3Status;
		private global::Gtk.Fixed fixedPC1;
		private global::Gtk.Label PC1Name;
		private global::Gtk.Label PC1HP;
		private global::Gtk.Label PC1MP;
		private global::Gtk.Label PC1Status;
		private global::Gtk.Fixed fixedPC2;
		private global::Gtk.Label PC2HP;
		private global::Gtk.Label PC2MP;
		private global::Gtk.Label PC2Status;
		private global::Gtk.Label PC2Name;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Button skillButton1;
		private global::Gtk.Button skillButton2;
		private global::Gtk.Button skillButton3;
		private global::Gtk.Button skillButton4;
		private global::Gtk.VPaned vpaned2;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Button menuButton;
		private global::Gtk.Button partyButton;
		private global::Gtk.Label roundCounter;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView Text;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget battle.MainWindow
			this.Name = "battle.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child battle.MainWindow.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 338;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 320;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(9));
			this.table1.ColumnSpacing = ((uint)(2));
			this.table1.BorderWidth = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.fixed10 = new global::Gtk.Fixed ();
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.PC3Name = new global::Gtk.Label ();
			this.PC3Name.Name = "PC3Name";
			this.fixed10.Add (this.PC3Name);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.PC3Name]));
			w1.X = 27;
			w1.Y = 10;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.PC3HP = new global::Gtk.Label ();
			this.PC3HP.Name = "PC3HP";
			this.fixed10.Add (this.PC3HP);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.PC3HP]));
			w2.X = 1;
			w2.Y = 30;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.PC3MP = new global::Gtk.Label ();
			this.PC3MP.Name = "PC3MP";
			this.fixed10.Add (this.PC3MP);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.PC3MP]));
			w3.X = 2;
			w3.Y = 45;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.PC3Status = new global::Gtk.Label ();
			this.PC3Status.Name = "PC3Status";
			this.fixed10.Add (this.PC3Status);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.PC3Status]));
			w4.X = 2;
			w4.Y = 61;
			this.table1.Add (this.fixed10);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed10]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fixedNPC1 = new global::Gtk.Fixed ();
			this.fixedNPC1.Name = "fixedNPC1";
			this.fixedNPC1.HasWindow = false;
			// Container child fixedNPC1.Gtk.Fixed+FixedChild
			this.NPC1Name = new global::Gtk.Label ();
			this.NPC1Name.Name = "NPC1Name";
			this.fixedNPC1.Add (this.NPC1Name);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC1 [this.NPC1Name]));
			w6.X = 3;
			w6.Y = 9;
			// Container child fixedNPC1.Gtk.Fixed+FixedChild
			this.NPC1HP = new global::Gtk.Label ();
			this.NPC1HP.Name = "NPC1HP";
			this.fixedNPC1.Add (this.NPC1HP);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC1 [this.NPC1HP]));
			w7.X = 26;
			w7.Y = 22;
			// Container child fixedNPC1.Gtk.Fixed+FixedChild
			this.NPC1MP = new global::Gtk.Label ();
			this.NPC1MP.Name = "NPC1MP";
			this.fixedNPC1.Add (this.NPC1MP);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC1 [this.NPC1MP]));
			w8.X = 26;
			w8.Y = 37;
			// Container child fixedNPC1.Gtk.Fixed+FixedChild
			this.NPC1Status = new global::Gtk.Label ();
			this.NPC1Status.Name = "NPC1Status";
			this.fixedNPC1.Add (this.NPC1Status);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC1 [this.NPC1Status]));
			w9.X = 25;
			w9.Y = 52;
			this.table1.Add (this.fixedNPC1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixedNPC1]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fixedNPC2 = new global::Gtk.Fixed ();
			this.fixedNPC2.Name = "fixedNPC2";
			this.fixedNPC2.HasWindow = false;
			// Container child fixedNPC2.Gtk.Fixed+FixedChild
			this.NPC2Name = new global::Gtk.Label ();
			this.NPC2Name.Name = "NPC2Name";
			this.fixedNPC2.Add (this.NPC2Name);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC2 [this.NPC2Name]));
			w11.X = 4;
			w11.Y = 23;
			// Container child fixedNPC2.Gtk.Fixed+FixedChild
			this.NPC2HP = new global::Gtk.Label ();
			this.NPC2HP.Name = "NPC2HP";
			this.fixedNPC2.Add (this.NPC2HP);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC2 [this.NPC2HP]));
			w12.X = 28;
			w12.Y = 37;
			// Container child fixedNPC2.Gtk.Fixed+FixedChild
			this.NPC2MP = new global::Gtk.Label ();
			this.NPC2MP.Name = "NPC2MP";
			this.fixedNPC2.Add (this.NPC2MP);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC2 [this.NPC2MP]));
			w13.X = 27;
			w13.Y = 50;
			// Container child fixedNPC2.Gtk.Fixed+FixedChild
			this.NPC2Status = new global::Gtk.Label ();
			this.NPC2Status.Name = "NPC2Status";
			this.fixedNPC2.Add (this.NPC2Status);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC2 [this.NPC2Status]));
			w14.X = 26;
			w14.Y = 65;
			this.table1.Add (this.fixedNPC2);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixedNPC2]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fixedNPC3 = new global::Gtk.Fixed ();
			this.fixedNPC3.Name = "fixedNPC3";
			this.fixedNPC3.HasWindow = false;
			// Container child fixedNPC3.Gtk.Fixed+FixedChild
			this.NPC3Name = new global::Gtk.Label ();
			this.NPC3Name.Name = "NPC3Name";
			this.fixedNPC3.Add (this.NPC3Name);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC3 [this.NPC3Name]));
			w16.Y = 9;
			// Container child fixedNPC3.Gtk.Fixed+FixedChild
			this.NPC3HP = new global::Gtk.Label ();
			this.NPC3HP.Name = "NPC3HP";
			this.fixedNPC3.Add (this.NPC3HP);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC3 [this.NPC3HP]));
			w17.X = 26;
			w17.Y = 26;
			// Container child fixedNPC3.Gtk.Fixed+FixedChild
			this.NPC3MP = new global::Gtk.Label ();
			this.NPC3MP.Name = "NPC3MP";
			this.fixedNPC3.Add (this.NPC3MP);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC3 [this.NPC3MP]));
			w18.X = 25;
			w18.Y = 41;
			// Container child fixedNPC3.Gtk.Fixed+FixedChild
			this.NPC3Status = new global::Gtk.Label ();
			this.NPC3Status.Name = "NPC3Status";
			this.fixedNPC3.Add (this.NPC3Status);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixedNPC3 [this.NPC3Status]));
			w19.X = 25;
			w19.Y = 55;
			this.table1.Add (this.fixedNPC3);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixedNPC3]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fixedPC1 = new global::Gtk.Fixed ();
			this.fixedPC1.Name = "fixedPC1";
			this.fixedPC1.HasWindow = false;
			// Container child fixedPC1.Gtk.Fixed+FixedChild
			this.PC1Name = new global::Gtk.Label ();
			this.PC1Name.Name = "PC1Name";
			this.PC1Name.Xalign = 0F;
			this.fixedPC1.Add (this.PC1Name);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixedPC1 [this.PC1Name]));
			w21.X = 24;
			w21.Y = 4;
			// Container child fixedPC1.Gtk.Fixed+FixedChild
			this.PC1HP = new global::Gtk.Label ();
			this.PC1HP.Name = "PC1HP";
			this.PC1HP.Xalign = 0F;
			this.fixedPC1.Add (this.PC1HP);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixedPC1 [this.PC1HP]));
			w22.X = 4;
			w22.Y = 20;
			// Container child fixedPC1.Gtk.Fixed+FixedChild
			this.PC1MP = new global::Gtk.Label ();
			this.PC1MP.Name = "PC1MP";
			this.fixedPC1.Add (this.PC1MP);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixedPC1 [this.PC1MP]));
			w23.X = 3;
			w23.Y = 32;
			// Container child fixedPC1.Gtk.Fixed+FixedChild
			this.PC1Status = new global::Gtk.Label ();
			this.PC1Status.Name = "PC1Status";
			this.fixedPC1.Add (this.PC1Status);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixedPC1 [this.PC1Status]));
			w24.X = 3;
			w24.Y = 46;
			this.table1.Add (this.fixedPC1);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixedPC1]));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fixedPC2 = new global::Gtk.Fixed ();
			this.fixedPC2.Name = "fixedPC2";
			this.fixedPC2.HasWindow = false;
			// Container child fixedPC2.Gtk.Fixed+FixedChild
			this.PC2HP = new global::Gtk.Label ();
			this.PC2HP.Name = "PC2HP";
			this.PC2HP.Xalign = 0F;
			this.fixedPC2.Add (this.PC2HP);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixedPC2 [this.PC2HP]));
			w26.X = 4;
			w26.Y = 24;
			// Container child fixedPC2.Gtk.Fixed+FixedChild
			this.PC2MP = new global::Gtk.Label ();
			this.PC2MP.Name = "PC2MP";
			this.fixedPC2.Add (this.PC2MP);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixedPC2 [this.PC2MP]));
			w27.X = 4;
			w27.Y = 37;
			// Container child fixedPC2.Gtk.Fixed+FixedChild
			this.PC2Status = new global::Gtk.Label ();
			this.PC2Status.Name = "PC2Status";
			this.fixedPC2.Add (this.PC2Status);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixedPC2 [this.PC2Status]));
			w28.X = 1;
			w28.Y = 50;
			// Container child fixedPC2.Gtk.Fixed+FixedChild
			this.PC2Name = new global::Gtk.Label ();
			this.PC2Name.Name = "PC2Name";
			this.fixedPC2.Add (this.PC2Name);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixedPC2 [this.PC2Name]));
			w29.X = 18;
			w29.Y = 6;
			this.table1.Add (this.fixedPC2);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixedPC2]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vpaned1.Add (this.table1);
			global::Gtk.Paned.PanedChild w31 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.table1]));
			w31.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.skillButton1 = new global::Gtk.Button ();
			this.skillButton1.CanFocus = true;
			this.skillButton1.Name = "skillButton1";
			this.skillButton1.UseUnderline = true;
			this.skillButton1.Label = global::Mono.Unix.Catalog.GetString ("Skill 1");
			this.fixed2.Add (this.skillButton1);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.skillButton1]));
			w32.X = 5;
			w32.Y = 4;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.skillButton2 = new global::Gtk.Button ();
			this.skillButton2.CanFocus = true;
			this.skillButton2.Name = "skillButton2";
			this.skillButton2.UseUnderline = true;
			this.skillButton2.Label = global::Mono.Unix.Catalog.GetString ("Skill 2");
			this.fixed2.Add (this.skillButton2);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.skillButton2]));
			w33.X = 5;
			w33.Y = 32;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.skillButton3 = new global::Gtk.Button ();
			this.skillButton3.CanFocus = true;
			this.skillButton3.Name = "skillButton3";
			this.skillButton3.UseUnderline = true;
			this.skillButton3.Label = global::Mono.Unix.Catalog.GetString ("Skill 3");
			this.fixed2.Add (this.skillButton3);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.skillButton3]));
			w34.X = 79;
			w34.Y = 4;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.skillButton4 = new global::Gtk.Button ();
			this.skillButton4.CanFocus = true;
			this.skillButton4.Name = "skillButton4";
			this.skillButton4.UseUnderline = true;
			this.skillButton4.Label = global::Mono.Unix.Catalog.GetString ("Skill 4");
			this.fixed2.Add (this.skillButton4);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.skillButton4]));
			w35.X = 79;
			w35.Y = 32;
			this.vpaned1.Add (this.fixed2);
			this.hpaned1.Add (this.vpaned1);
			global::Gtk.Paned.PanedChild w37 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vpaned1]));
			w37.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 83;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.menuButton = new global::Gtk.Button ();
			this.menuButton.CanFocus = true;
			this.menuButton.Name = "menuButton";
			this.menuButton.UseUnderline = true;
			this.menuButton.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.fixed1.Add (this.menuButton);
			global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.menuButton]));
			w38.X = 208;
			w38.Y = 51;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.partyButton = new global::Gtk.Button ();
			this.partyButton.CanFocus = true;
			this.partyButton.Name = "partyButton";
			this.partyButton.UseUnderline = true;
			this.partyButton.Label = global::Mono.Unix.Catalog.GetString ("Party");
			this.fixed1.Add (this.partyButton);
			global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.partyButton]));
			w39.X = 7;
			w39.Y = 6;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.roundCounter = new global::Gtk.Label ();
			this.roundCounter.Name = "roundCounter";
			this.roundCounter.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.fixed1.Add (this.roundCounter);
			global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.roundCounter]));
			w40.X = 215;
			w40.Y = 5;
			this.vpaned2.Add (this.fixed1);
			global::Gtk.Paned.PanedChild w41 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.fixed1]));
			w41.Resize = false;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.Text = new global::Gtk.TextView ();
			this.Text.CanFocus = true;
			this.Text.Name = "Text";
			this.Text.Editable = false;
			this.GtkScrolledWindow.Add (this.Text);
			this.vpaned2.Add (this.GtkScrolledWindow);
			this.hpaned1.Add (this.vpaned2);
			this.Add (this.hpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 605;
			this.DefaultHeight = 394;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.skillButton1.Released += new global::System.EventHandler (this.OnSkillButton1Released);
			this.skillButton2.Released += new global::System.EventHandler (this.OnSkillButton2Released);
			this.skillButton3.Released += new global::System.EventHandler (this.OnSkillButton3Released);
			this.skillButton4.Released += new global::System.EventHandler (this.OnSkillButton4Released);
			this.partyButton.Released += new global::System.EventHandler (this.PartySelect);
		}
	}
}
